### ISSUE TITLE
We need some imagery with people in them

### ISSUE THREAD

**Issue by LouiseMcMahon** [sheffieldhackspace/Public-Website#22]
Images to capture
- [x] Someone soldering at the soldering station.
- [x] Someone using one of the lathes.
- [ ] A photo of several people sitting at the big table discussing a project
- [ ] A photo of several people stood around the whiteboard.
- [x] Someone using a grinder.
- [x] Someone using the laser cutter

**Comment by themanontv** [comment]
If you need someone to bring in a fancy camera I can bring one in so some photos can be staged?

**Comment by tennessee1227** [comment]
If you were to stage a photo of people around the big table it might be worth filling it with people less than (or equal to) 30 years old...

**Comment by themanontv** [comment]
Got a few photos of the laser cutter and one of the 3d printer
