### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by LouiseMcMahon** [sheffieldhackspace/Public-Website#25]
Do we even need it? Can we just have static text that lists the opening dates?

**Comment by aur0us** [comment]
Its nice to have for games but I guess those only apply for concurrent members, I think listing dates + times would be better and sending off emails for special events like the AGM

**Comment by themanontv** [comment]
Do we have irregular events or changes in schedule that couldn't be addressed by a static disclaimer on the site? Would we need something that regularly updates with a feed (which would amount to a dynamic list) or would just a static list suffice?

**Comment by tennessee1227** [comment]
Nearly all of the sessions are fixed and don't need a calendar. And a link to Sheffield United's fixtures with an explanation would probably suffice for parking issues

**Comment by tennessee1227** [comment]
For games night you could mention that it's on every other Saturday and to email us for more details or something like that? Or leave it off since it's really only for existing members

**Comment by themanontv** [comment]
In theory could the games scheduling just be handled by the discord?

**Comment by tennessee1227** [comment]
Could be yeah

**Comment by aur0us** [comment]
game night being by discord sounds perfect, since they do online every other week. We could give them a special role that people can opt into if they are interested so that they get pinged
