### ISSUE TITLE
Migrate posts from WP website

### ISSUE THREAD

**Issue by LouiseMcMahon** [sheffieldhackspace/Public-Website#5]
It would be good to try and preserve the existing URLs so any inbound links continue to work.

This plugin can do the export from us https://wordpress.org/plugins/jekyll-exporter/. I expect they will need some tidying after and checking over to make sure all the images and videos etc have been exported.

**Comment by LouiseMcMahon** [comment]
Will need some help from someone that has access to the WP website (i don't)

**Comment by RincewindLangner** [comment]
I may need some points but I could help port some across.

**Comment by LouiseMcMahon** [comment]
Posts have been migrated and trimmed
