### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by alifeee** [sheffieldhackspace/Public-Website#74]
before, I was able to push branches to this repository

now, I must create a fork

![image](https://github.com/user-attachments/assets/515794f6-6abf-47d5-89d4-3d1963a1f34a)

it would be nice for hackspace members to be able to create branches here. I know @LouiseMcMahon changed the permissions recently, so maybe this is not possible (at the same time as requiring PR approvals by trustees only). If so, please close this.

**Comment by LouiseMcMahon** [comment]
Yep thats the issue now we have added a lot more members to the team we needed to lock it down properly

**Comment by alifeee** [comment]
hm, I thought there was a way to have members able to create branches and not push to main without a review, and to set who is allowed to review. But I think you can't set specific review requirements, so fair enough :)
